server:
  port: 9000
  servlet:
    context-path: "/bms"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #  redis:
    #    host: localhost
    #    port: 6379
    #    password:
    #    database: 0
    #    lettuce:
    #      pool:
    #        max-active: 20
    #        max-idle: 10
    #        min-idle: 0
    #    timeout: 10000
    redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 30000
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000
        address: redis://localhost:6379


#rocketmq
rocketmq:
  name-server: 192.168.195.128:9876
  producer:
    group: uniqueSpringBootGroup
  consumer:
    group: test-group

logging:
  level:
    com.example.mp.controller: info
    com.example.mp.service: info
    com.example.mp.mapper: debug
  pattern:
    dateformat: HH:mm:ss

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


